--- 
build_requires: 
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.67
license: Perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Jifty
no_index: 
  directory: 
    - debian
    - doc
    - examples
    - share
    - plugins/*/t
    - inc
    - t
  package: 
    - DB
recommends: 
  Apache2::Const: 0
  Authen::CAS::Client: 0
  Cache::FileCache: 0
  Chart::Base: 0
  Class::Accessor::Named: 0
  Crypt::OpenSSL::RSA: 0
  DBD::SQLite: 0
  Devel::Cover: 0
  Devel::EvalContext: 0
  Devel::Events: 0.02
  Devel::Events::Generator::Objects: 0
  Devel::Events::Handler::ObjectTracker: 0
  Devel::Size: 0
  Digest::HMAC_SHA1: 0
  GD: 0
  GD::Graph: 0
  Image::Info: 0
  LWPx::ParanoidAgent: 0
  Module::CoreList: 0
  Module::Install::Admin: 0.50
  Module::Refresh: 0.09
  Net::LDAP: 0
  Net::OAuth::AccessTokenRequest: 0
  Net::OAuth::ProtectedResourceRequest: 0
  Net::OAuth::Request: 0.04
  Net::OAuth::RequestTokenRequest: 0
  Net::OpenID::Consumer: 0
  Net::Server::Fork: 0
  Net::Server::PreFork: 0
  PAR::Dist::FromCPAN: 0
  Proc::ProcessTable: 0
  Test::Base: 0.44
  Test::HTML::Lint: 0
  Test::HTTP::Server::Simple: 0.02
  Test::MockModule: 0.05
  Test::MockObject: 1.07
  Test::WWW::Declare: 0.01
  WWW::Facebook::API: 0.3.6
  XML::Simple: 0
requires: 
  App::CLI: 0.03
  CGI: 3.19
  CGI::Cookie::Splitter: 0
  CSS::Squish: 0.07
  Cache::Cache: 0
  Calendar::Simple: 0
  Class::Accessor: 0
  Class::Container: 0
  Class::Data::Inheritable: 0
  Class::Trigger: 0.12
  Clone: 0.27
  Compress::Zlib: 0
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  DBD::SQLite: 1.11
  Data::Page: 0
  Data::UUID: 0
  Date::Manip: 0
  DateTime: 0
  DateTime::Locale: 0
  Email::Folder: 0
  Email::LocalDelivery: 0.217
  Email::MIME: 0
  Email::MIME::ContentType: 0
  Email::MIME::CreateHTML: 0
  Email::MIME::Creator: 0
  Email::MIME::Modifier: 0
  Email::Send: 1.99_01
  Email::Simple: 0
  Email::Simple::Creator: 0
  Exporter::Lite: 0
  File::Find::Rule: 0
  File::MMagic: 0
  File::ShareDir: 0.04
  File::Spec: 3.14
  File::Temp: 0.15
  HTML::Entities: 0
  HTML::Lint: 0
  HTML::Mason: 1.3101
  HTML::Mason::Plugin: 0
  HTTP::Cookies: 0
  HTTP::Date: 0
  HTTP::Server::Simple: 0.26
  HTTP::Server::Simple::Recorder: 0
  Hash::Merge: 0
  Hook::LexWrap: 0
  IPC::PubSub: 0.23
  IPC::Run3: 0
  JSON::Syck: 0.15
  Jifty::DBI: 0.47
  LWP::UserAgent: 0
  Locale::Maketext::Extract: 0.20
  Locale::Maketext::Lexicon: 0.60
  Log::Log4perl: 1.04
  MIME::Types: 0
  Module::CoreList: 0
  Module::Pluggable: 3.5
  Module::Pluggable::Object: 0
  Module::Refresh: 0
  Module::ScanDeps: 0
  Object::Declare: 0.13
  PadWalker: 0
  Params::Validate: 0
  Pod::Simple: 0
  SQL::ReservedWords: 0
  Scalar::Defer: 0.10
  Shell::Command: 0
  String::Koremutake: 0
  Template::Declare: 0.26
  Test::Base: 0
  Test::Log4perl: 0
  Test::LongString: 0
  Test::More: 0.62
  Test::Pod::Coverage: 0
  Test::WWW::Mechanize: 1.04
  Test::WWW::Selenium: 0
  UNIVERSAL::require: 0
  URI: 1.31
  WWW::Mechanize: 1.3
  XML::Simple: 0
  XML::Writer: 0.601
  XML::XPath: 0
  YAML: 0.35
  YAML::Syck: 0.71
  perl: 5.8.3
  version: 0
tests: t/*.t t/*/*.t t/*/*/*.t t/*/*/*/*.t
version: 0.71129
