#!/usr/bin/perl

use warnings;
use strict;
use Term::ANSIScreen qw/:color :cursor :screen :keyboard/;
use Term::ReadKey;
use Text::Autoformat;
our @SLIDES;

load_slides();
my $counter = 0;
my $slides_played = {};
	my $title;
while ( $counter <= $#SLIDES ) {
    my $mode = 'text';
    my ( $cols, $rows, undef, undef ) = GetTerminalSize();
    my $slide = $SLIDES[$counter];
    my $console = Term::ANSIScreen->new;
    $console->Cls;
    $console->Cursor(1,1);
    if ( $slide =~ s/^#\s*title\s*?(.*?)$//gm ) {
        $title = $1;
    }
	if ($title) {
        my $start = int ( ( $cols / 2 ) - ( length($title) / 2 ) );
	$console->Cursor($start,0);
	chomp $title;
	print "$title\n";
	}

    if ($slide =~ s/#\s*`(.*?)`//m) {
	my $cmd = $1;
	if(!$slides_played->{$counter}) {
	`$cmd>/dev/null 2>/dev/null &`;
	$slides_played->{$counter}++}
    }
    if ( $slide =~ s/#\s*mode.*?perl.*?$//gms ) {
        $mode = 'perl';
    }
    if ( $mode eq 'text' and $slide ) {
        $slide = autoformat $slide, { left => 1, right => ($cols-1), all => 1 };
    }
    elsif ($mode eq 'perl') {
	my $tidycols = $cols - 2; # squeeze for display
	open my $out , ">/tmp/output.$$" || die $!;
	print $out $slide || die $!;
	close $out || die $!;
	$slide = ` cat /tmp/output.$$ | source-highlight -s perl -f esc`;
	#$slide = ` cat /tmp/output.$$ | perltidy -q -l $tidycols| source-highlight -s perl -f esc`;
    }
 
    if ( $slide =~ /(\S+)\s*\n\s*(\S+)/m ) {
	my $lines = scalar split(/\n/,$slide);
	$console->Cursor(0, int(($rows/2)-($lines/2))-1);
    	print $slide;
    } else {
	chomp $slide;
	$slide =~ s/(?:\n|\r)//g;
		my $left = int ( ( $cols / 2 ) - ( length($slide) / 2 ) ); 
	if ($left < 0 ){
		$left = 0;
	}
        $console->Cursor( $left,	int($rows/2)-1, );
	print $slide."\n";
    }


    $console->Cursor( 0, ( $rows - 1 ) );
    print "$counter/" . $#SLIDES;
    ReadMode 4;
    my $key = ReadKey(0);
    ReadMode 0;
    if ( $key eq 'q' ) {
        exit;
    }
    if ( $key =~ /^(?: |\n|n)/ ) {
        $counter++;
    } elsif ( $key eq 'r' ) {
	load_slides();
        next;

    } else {
        $counter--;
        if ( $counter < 0 ) {
            $counter = 0;
        }
    }
}

sub load_slides {
my $file = $ARGV[0];
my $handle;
open( $handle, "<$file" ) || die $!;

my $datadata = join( '', <$handle> );

 @SLIDES  = split( /^----?\s*$/mi, $datadata );
}
